version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    ECR_REPO_URI: 153402911459.dkr.ecr.us-east-1.amazonaws.com/bbmeet-api
    IMAGE_TAG: latest
    ECS_CLUSTER: bbmeet-cluster
    ECS_SERVICE: bbmeet-api-service
    SSM_PARAM_PATH: /bbmeet/production/api

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y jq aws-cli || dnf install -y jq aws-cli

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI

  build:
    commands:
      - echo "Building Docker image..."
      - cd bb-sdk-api
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - echo "Updating ECS Service..."
      - |
        if aws ecs describe-services --cluster $ECS_CLUSTER --services $ECS_SERVICE | grep -q "MISSING"; then
          echo "Service $ECS_SERVICE does not exist yet. Skipping update."
        else
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
        fi
      - echo "Deployment completed!"

artifacts:
  files:
    - '**/*'
