version: 0.2
env:
  variables:
    MEDIA_HOST: 3.215.239.166
    MEDIA_USER: ec2-user
    SSM_PARAM: /bbmeet/ec2-ssh-key
    RUST_BACKTRACE: "1"

phases:
      install:
        commands:
          - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          - source $HOME/.cargo/env
          - rustup toolchain install stable
          - rustup default stable
          - rustc --version
          - cargo --version
          - dnf install -y gcc gcc-c++ make cmake clang pkg-config openssl-devel protobuf-compiler protobuf-devel openssl
          - dnf install -y aws-cli || yum install -y aws-cli
          - mkdir -p ~/.ssh
          - aws ssm get-parameter --name "$SSM_PARAM" --with-decryption --query "Parameter.Value" --output text > ~/.ssh/deploy_key.pem
          - chmod 600 ~/.ssh/deploy_key.pem
          - ssh-keyscan -H "$MEDIA_HOST" >> ~/.ssh/known_hosts 2>/dev/null || true
          - |
            # Generate self-signed certificates for TLS (required at compile time)
            cd bb-sdk-media
            mkdir -p certificates
            if [ ! -f certificates/cert.pem ] || [ ! -f certificates/key.pem ]; then
              openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 \
                -keyout certificates/key.pem \
                -out certificates/cert.pem \
                -days 365 \
                -nodes \
                -subj "/CN=localhost" 2>&1 || echo "Warning: Failed to generate certificates"
              ls -la certificates/ || echo "Certificates directory check failed"
            fi

  build:
    commands:
      - source $HOME/.cargo/env
      - cd bb-sdk-media
      - |
        # Ensure certificates exist before build (fallback if install phase didn't create them)
        if [ ! -f certificates/cert.pem ] || [ ! -f certificates/key.pem ]; then
          echo "Certificates not found, generating..."
          mkdir -p certificates
          openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 \
            -keyout certificates/key.pem \
            -out certificates/cert.pem \
            -days 365 \
            -nodes \
            -subj "/CN=localhost" 2>&1
          echo "Certificate generation complete"
        fi
        ls -la certificates/ || echo "Warning: Cannot list certificates directory"
      - echo "Building CORE components - signalling + sfu + webrtc-manager"
      - cargo build --release --workspace --exclude egress-manager
      - ls -lh target/release/signalling target/release/sfu
      - tar -czf ../media-core-deploy.tar.gz target/release/signalling target/release/sfu
      - scp -i ~/.ssh/deploy_key.pem -o StrictHostKeyChecking=no ../media-core-deploy.tar.gz "$MEDIA_USER@$MEDIA_HOST:~/"
      - |
        cat <<'EOF' > deploy-core.sh
        #!/bin/bash
        cd ~/bb-sdk-media || mkdir -p ~/bb-sdk-media && cd ~/bb-sdk-media
        tar -xzf ~/media-core-deploy.tar.gz
        rm ~/media-core-deploy.tar.gz
        chmod +x target/release/signalling target/release/sfu
        pkill -f signalling || true
        pkill -f sfu || true
        nohup ./target/release/signalling > ~/signalling.log 2>&1 &
        nohup ./target/release/sfu > ~/sfu.log 2>&1 &
        sleep 2
        ps aux | grep -E "(signalling|sfu)" | grep -v grep
        echo "CORE media services restarted successfully"
        EOF
      - scp -i ~/.ssh/deploy_key.pem -o StrictHostKeyChecking=no deploy-core.sh "$MEDIA_USER@$MEDIA_HOST:~/"
      - ssh -i ~/.ssh/deploy_key.pem -o StrictHostKeyChecking=no "$MEDIA_USER@$MEDIA_HOST" "bash ~/deploy-core.sh"

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.cargo/registry/**/*'
    - '/root/.cargo/git/**/*'
    - 'bb-sdk-media/target/**/*'
